version: 0.2
environment_variables:
  plaintext:
    NODE_ENV: "unittest"
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm install -g jovo-cli
      - npm install --save-dev
  pre_build:
    commands:
      - npm test
  build:
    commands:
      - npm run bundle
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml

artifacts:
  type: zip
  files:
    - template-export.yml
